# Generated by Django 5.2.1 on 2025-05-13 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_alter_blogpost_content_alter_page_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='is_crm_synced',
            field=models.BooleanField(default=False),
        ),
    ]
