# Generated by Django 5.2.1 on 2025-05-13 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0003_property_is_crm_synced'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='manual_overide',
            field=models.BooleanField(default=False),
        ),
    ]
