# Generated by Django 5.2.1 on 2025-05-14 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0004_property_manual_overide'),
    ]

    operations = [
        migrations.RenameField(
            model_name='property',
            old_name='manual_overide',
            new_name='manual_override',
        ),
    ]
